# use vim as the visual editor
source "$HOME/.zsh/functions/is_os"

export VISUAL=nvim
export EDITOR=$VISUAL

# ensure dotfiles bin directory is loaded first
export PATH="$HOME/.local/bin:$PATH"

# Use bat for man if available
if type "bat" > /dev/null; then
  # 2023.16.10 I had to add this, otherwise manpages would show shell color
  # codes within the documentation.
  export MANROFFOPT="-c"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local
