name: Rolling Release
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.generatePackages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - id: releaseWslTarbal
        run: |
          nix develop --command gh-release-wsl-tarbal
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
